version: "2.1"
services:

  scheduled_job:
    build: ./scheduled_job
    depends_on:
      db:
        condition: service_healthy
    networks:
     - oracle
  
  db:
    image: store/oracle/database-enterprise:12.2.0.1
    ports:
      - "1521:1521"
    networks:
     - oracle
  
networks:
  oracle:
    driver: "bridge"