version: "3.3"
services:

  scheduled_job:
    build: ./scheduled_job
    entrypoint: ["./wait-for-it.sh", "db:1521", "--timeout=0", "--strict", "--", "/bin/bash", "-c", "crond && tail -f /var/log/cron.log" ]
    depends_on:
      - db
    networks:
     - oracle
  
  db:
    image: store/oracle/database-enterprise:12.2.0.1
    ports:
      - "1521:1521"
    networks:
     - oracle
  
networks:
  oracle:
    driver: "bridge"