version: "3.3"
services:

  scheduled_job:
    build: ./scheduled_job
    depends_on:
      - db
    networks:
     - oracle
  
  db:
    image: store/oracle/database-enterprise:12.2.0.1
    ports:
      - "1521:1521"
    networks:
     - oracle
  
  db_bootstrap:
    build: ./db_bootstrap
    depends_on:
      - db
    networks:
      - oracle

networks:
  oracle:
    driver: "bridge"